### ISSUE TITLE
TODO list pinocchio

### ISSUE THREAD

**Issue by pFernbach** [humanoid-path-planner/hpp-core#56]
- [x] **distance-between-objects.cc**   switch to GeomData (copy from Device::geomData_, empty the collision pair list and add them as you did)
- [x] **locked-joint.cc** Partial locked joints may be double checked later
- [x] **path-optimization/collision-constraints-result.hh** eigen::vector3_t => vector3_t
- [ ] **parser/roadmap-factory.cc** has to be revised as, so far, the XML parser is not available.
- [x] **relative-motion.cc** getNonAnchorParent can probably be removed
- [x] **reeds-shepp-path.cc** update check of joint types
- [x] **weighed-distance.cc** reimplemente / update children iterator
